version: '2.0'

networks:
  guacnetwork_compose:
    driver: bridge

services:
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: unless-stopped
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      guacnetwork_compose:
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data:rw

  guacamole:
    container_name: guacamole_compose
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      guacnetwork_compose:
    ports:
      - 8080/tcp
    restart: unless-stopped

  https-portal:
    container_name: https-portal_guacamole_compose
    image: steveltn/https-portal:1
    environment:
      DOMAINS: ${DOMAIN} -> http://guacamole:8080/guacamole/
      STAGE: ${HTTPS_PORTAL_STAGE}
    volumes:
      - https-portal_certs:/var/lib/https-portal
    networks:
      guacnetwork_compose:
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    restart: unless-stopped

volumes:
  https-portal_certs:
